name: Rakuten Availability Check

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前9時（日本時間）
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run checker script
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          RAKUTEN_URL: ${{ secrets.RAKUTEN_URL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python checker.py